/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.UsuariosBjf;
import dao.UsuariosDAOBjf;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import pesquisa.JDlgUsuariosPesquisaBjf;
import tools.Util;

/**
 *
 * @author 
 */
public class JDlgUsuariosBjf extends javax.swing.JDialog {
    public boolean incluindo;
    MaskFormatter mascaraCpf;
    MaskFormatter mascaraData;
    JDlgUsuariosPesquisaBjf jDlgUsuariosPesquisaBjf;
    UsuariosBjf usuariosBjf;
    UsuariosDAOBjf usuarioDAOBjf;
    
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuariosBjf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Usuarios");
        setLocationRelativeTo(null);
        
        Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        jBtnIncluir.setEnabled(true);
        Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        jDlgUsuariosPesquisaBjf = new JDlgUsuariosPesquisaBjf(null, modal);

       try {
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraData = new MaskFormatter("##/##/####");
            
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpfBjf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        jFmtDataNascimentoBjf.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
    }
    
     public UsuariosBjf viewBean() {
        UsuariosBjf usuariosBjf = new UsuariosBjf();
        int id = Util.strInt(jTxtCodigoBjf.getText());
        Date dataNascimento = Util.strDate(jFmtDataNascimentoBjf.getText());
        usuariosBjf.setIdusuariosBjf(id);
        usuariosBjf.setNomeBjf(jTxtNomeBjf.getText());
        usuariosBjf.setEmailBjf(jTxtEmailBjf.getText());
        usuariosBjf.setSenhaBjf(jPwfSenhaBjf.getText());
        usuariosBjf.setDataNascBjf(dataNascimento);

//        usuariosBjf.setSexoBjf(jCboSexo.getSelectedIndex());
        if(jChbAtivo.isSelected()==true){
        usuariosBjf.setAtivoBjf("S");
        } else {
        usuariosBjf.setAtivoBjf("N");
        }
        
        return usuariosBjf;

    }

    public void beanView(UsuariosBjf usuariosBjf) {

        String intStr = Util.intStr(usuariosBjf.getIdusuariosBjf());
        String dataNascimento = Util.dateStr(usuariosBjf.getDataNascBjf());

        jTxtCodigoBjf.setText(intStr);
//        jFmtDataRegistro.setText(dataRegistroDate);
        jTxtNomeBjf.setText(usuariosBjf.getNomeBjf());
        jTxtEmailBjf.setText(usuariosBjf.getEmailBjf());
        jPwfSenhaBjf.setText(usuariosBjf.getSenhaBjf());
        jFmtDataNascimentoBjf.setText(dataNascimento);

        if(usuariosBjf.getAtivoBjf().equals("S") == true){
            jChbAtivo.setSelected(true);
        } else {
            jChbAtivo.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jFmtCpfBjf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnAlterar = new javax.swing.JButton();
        jTxtEmailBjf = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jTxtNomeBjf = new javax.swing.JTextField();
        jChbAtivo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCboSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtCodigoBjf = new javax.swing.JTextField();
        jPwfSenhaBjf = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jFmtDataNascimentoBjf = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("DATA DE NASCIMENTO:");

        jFmtCpfBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpfBjfActionPerformed(evt);
            }
        });

        jLabel3.setText("EMAIL:");

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jTxtEmailBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailBjfActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jTxtNomeBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeBjfActionPerformed(evt);
            }
        });

        jChbAtivo.setText("Ativo");

        jLabel2.setText("NOME:");

        jCboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSexoActionPerformed(evt);
            }
        });

        jLabel1.setText("Código:");

        jLabel7.setText("SEXO:");

        jTxtCodigoBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoBjfActionPerformed(evt);
            }
        });

        jLabel6.setText("SENHA:");

        jFmtDataNascimentoBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNascimentoBjfActionPerformed(evt);
            }
        });

        jLabel9.setText("Você está ativo?");

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 153));
        jLabel8.setText("Cadastro de Usuários");

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF:");

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPwfSenhaBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCpfBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtCodigoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jFmtDataNascimentoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEmailBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jCboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)))
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtDataNascimentoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCodigoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEmailBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCpfBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenhaBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCancelar)
                        .addComponent(jBtnPesquisar)
                        .addComponent(jBtnAlterar)
                        .addComponent(jBtnIncluir)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmtCpfBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpfBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpfBjfActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        if (Util.perguntar("Deseja alterar o registro?") == true) {
            
    }else{
        Util.mensagem("Alteração Cancelada.");
          
       }
        Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        //        habilitar();
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jTxtEmailBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailBjfActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
       
        jBtnIncluir.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnPesquisar.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        incluindo = true;
       


//        habilitar();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jTxtNomeBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeBjfActionPerformed

    private void jCboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboSexoActionPerformed

    private void jTxtCodigoBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoBjfActionPerformed

    private void jFmtDataNascimentoBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNascimentoBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataNascimentoBjfActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
         Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
         Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        
        //        desabilitar();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
     Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
      
     Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
     
        jDlgUsuariosPesquisaBjf.setTitle("Inclusão");
        jDlgUsuariosPesquisaBjf.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
//        UsuariosBjf usuariosBjf = viewbean();
        
        jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
        jBtnCancelar.setEnabled(false);

        UsuariosBjf usuariosBjf = viewBean();

        UsuariosDAOBjf usuariosDAOBjf = new UsuariosDAOBjf();//constroi o dao
        
        if (incluindo == true) {
            usuariosDAOBjf.insert(usuariosBjf);
            Util.mensagem("Usuario adicionado com sucesso!");
        } else {
            usuariosDAOBjf.update(usuariosBjf);
            Util.mensagem("Usuario alterado!");
        }

        
        Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        
        //        desabilitar();
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
    if (Util.perguntar("Deseja excluir o registro?") == true) {
            
    }else{
        Util.mensagem("Exclusão Cancelada.");
          
       }
     Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
     Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        
    // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuariosBjf dialog = new JDlgUsuariosBjf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboSexo;
    private javax.swing.JCheckBox jChbAtivo;
    private javax.swing.JFormattedTextField jFmtCpfBjf;
    private javax.swing.JFormattedTextField jFmtDataNascimentoBjf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPwfSenhaBjf;
    private javax.swing.JTextField jTxtCodigoBjf;
    private javax.swing.JTextField jTxtEmailBjf;
    private javax.swing.JTextField jTxtNomeBjf;
    // End of variables declaration//GEN-END:variables

}