/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ClienteBjf;
import dao.ClientesDAOBjf;
import java.util.Date;
import pesquisa.JDlgClientePesquisaBjf;
import tools.Util;

/**
 *
 * @author u03402615100
 */
public class JDlgClientesBjf extends javax.swing.JDialog {
 public boolean incluindo;
//    MaskFormatter mascaraCpf;
//    MaskFormatter mascaraData;
    JDlgClientePesquisaBjf jDlgClientePesquisaBjf;
    ClienteBjf clienteBjf;
    ClientesDAOBjf clientesDAOBjf;
    /**
     * Creates new form JDlgClientes
     */
    public JDlgClientesBjf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Clientes");
        setLocationRelativeTo(null);
        Util.habilitar(false, jFmtCodigo, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        jBtnIncluir.setEnabled(true);
        Util.limparCampos(jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         *
         * @return
         */
    }

    public ClienteBjf viewBean() {
        ClienteBjf cliente = new ClienteBjf();

        int id = Util.strInt(jFmtCodigo.getText());
        cliente.setIdclienteBjf(id);
        cliente.setNomeBjf(jTxtNomeBjf.getText());
       // Date dataNascimento = Util.strDate(jFmtDataNasc.getText());
       // cliente.setDataNascBjf(dataNascimento);
//        Date dataRegistro = Util.strDate(jFmtDataRegistro.getText());
//        cliente.setDataRegistroBjf(dataRegistro);
        cliente.setProfissaoBjf(jTxtProfissao.getText());
        cliente.setCpfBjf(jFmtCPFBjf.getText());
        cliente.setEmailBjf(jTxtEmail.getText());
        cliente.setRgBjf(jFmtRGBjf.getText());
        cliente.setEnderecoBjf(jTxtEndereço.getText());
        cliente.setCidadeBjf(jTxtCidade.getText());
        cliente.setTelefoneBjf(jFmtTelefoneBjf.getText());
        cliente.setEstadoBjf(jTxtEstado.getText());

        if ((jCboEstado.getSelectedIndex() == 1)) {
            cliente.setEstadoCivilBjf("Casado");
        } else if ((jCboEstado.getSelectedIndex() == 2)) {
            cliente.setEstadoCivilBjf("Solteiro");
        } else if ((jCboEstado.getSelectedIndex() == 3)) {
            cliente.setEstadoCivilBjf("Namorando");
        } else {
            cliente.setEstadoCivilBjf("Abandonado");
        }
        return cliente;
    }

 
    

    

    public void beanView(ClienteBjf cliente) {
        jFmtCodigo.setText(Util.intStr(cliente.getIdclienteBjf()));
        jTxtNomeBjf.setText(cliente.getNomeBjf());
        
        String estadoCivil =cliente.getEstadoCivilBjf();
        if(estadoCivil.equals("Casado")){
            jCboEstado.setSelectedIndex(0);
        }else if(estadoCivil.equals("Solteiro")){
            jCboEstado.setSelectedIndex(1);
        }else if(estadoCivil.equals("Divorciado")){
            jCboEstado.setSelectedIndex(2);
        }else {
            jCboEstado.setSelectedIndex(3);
        }
        
        jFmtCEP.setText(cliente.getCepBjf());
        jTxtProfissao.setText(cliente.getProfissaoBjf());
        jFmtCPFBjf.setText(cliente.getCpfBjf());
        jTxtEmail.setText(cliente.getEmailBjf());
        
//        jFmtDataNasc.setText(Util.dateStr(cliente.getDataNascBjf()));
//        jFmtDataRegistro.setText(Util.dateStr(cliente.getDataRegistroBjf()));
       jFmtRGBjf.setText(cliente.getRgBjf());
       jTxtEndereço.setText(cliente.getEnderecoBjf());
       jTxtCidade.setText(cliente.getCidadeBjf());
       jFmtTelefoneBjf.setText(cliente.getTelefoneBjf());
       jTxtEstado.setText(cliente.getEstadoBjf());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTxtCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jTxtProfissao = new javax.swing.JFormattedTextField();
        jFmtDataNasc = new javax.swing.JFormattedTextField();
        jCboEstado = new javax.swing.JComboBox<>();
        jLabelGenero = new javax.swing.JLabel();
        jTxtEndereço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtEstado = new javax.swing.JTextField();
        jFmtDataRegistro = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelNaturalidade = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jFmtCEP = new javax.swing.JFormattedTextField();
        jFmtCPFBjf = new javax.swing.JFormattedTextField();
        jFmtTelefoneBjf = new javax.swing.JFormattedTextField();
        jTxtNomeBjf = new javax.swing.JTextField();
        jBtnCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFmtCodigo = new javax.swing.JFormattedTextField();
        jFmtRGBjf = new javax.swing.JFormattedTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 153));
        jLabel1.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Cadastro de Clientes");

        jLabelCPF.setText("CPF");

        jCboEstado.setForeground(new java.awt.Color(255, 0, 153));
        jCboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASADO", "SOLTEIRO", "NAMORANDO", "ABANDONADO", " " }));
        jCboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboEstadoActionPerformed(evt);
            }
        });

        jLabelGenero.setForeground(new java.awt.Color(102, 0, 102));
        jLabelGenero.setText("Estado Civil");

        jLabel5.setText("Telefone");

        jLabel4.setText("Data de Nascimento");

        jFmtDataRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataRegistroActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jLabel9.setText("Profissão");

        jLabelNaturalidade.setText("Endereço");

        jLabelEmail.setText("Email");

        jLabelNome.setText("Nome");

        jFmtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCEPActionPerformed(evt);
            }
        });

        jFmtCPFBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCPFBjfActionPerformed(evt);
            }
        });

        jTxtNomeBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeBjfActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel14.setText("CEP");

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado");

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel12.setText("Cidade ");

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jLabel10.setText("Data Registro");

        jLabel2.setText("RG");

        jLabel3.setText("Código:");

        jFmtRGBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtRGBjfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnIncluir)
                                .addGap(17, 17, 17)
                                .addComponent(jBtnAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnExcluir)
                                .addGap(26, 26, 26)
                                .addComponent(jBtnConfirmar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFmtDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jFmtRGBjf))
                                .addGap(252, 252, 252)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEstado)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(0, 231, Short.MAX_VALUE))
                                    .addComponent(jTxtCidade))))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFmtCPFBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCPF)
                            .addComponent(jLabelNome))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(168, 168, 168)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(130, 130, 130))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFmtTelefoneBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTxtEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNaturalidade)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelGenero))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jFmtCEP))))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtProfissao)
                                    .addComponent(jFmtDataRegistro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCPFBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtRGBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabelEmail)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelGenero)
                                .addComponent(jLabel14)
                                .addComponent(jLabel9))
                            .addGap(8, 8, 8)
                            .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtDataRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNaturalidade)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(jFmtTelefoneBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnPesquisar)
                        .addComponent(jBtnCancelar))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboEstadoActionPerformed

    private void jFmtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCEPActionPerformed

    private void jFmtCPFBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCPFBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCPFBjfActionPerformed

    private void jTxtNomeBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeBjfActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed

        Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.limparCampos(jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
       
        JDlgClientePesquisaBjf jDlgClientePesquisaBjf = new JDlgClientePesquisaBjf(null, true);
//        jDlgClientePesquisaBjf.setTelaAnterior(this);
        jDlgClientePesquisaBjf.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.limparCampos(jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        //        desabilitar();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        Util.habilitar(true, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        //        habilitar();
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.limparCampos(jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);            //
        
        
          jBtnIncluir.setEnabled(true);
        jBtnPesquisar.setEnabled(true);
        jBtnCancelar.setEnabled(false);

      clienteBjf = viewBean();

         clientesDAOBjf = new ClientesDAOBjf();//constroi o dao
        
        if (incluindo == true) {
            clientesDAOBjf.insert(clienteBjf);
            Util.mensagem("Cliente adicionado ");
        } else {
            clientesDAOBjf.update(clienteBjf);
            Util.mensagem("Cliente alterado!");
        }
        
//        desabilitar();
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        //        habilitar();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        Util.limparCampos(jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.habilitar(false, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        if (Util.perguntar("Deseja excluir o registro?") == true) {

        } else {
            Util.mensagem("Exclusão Cancelada.");

        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jFmtRGBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtRGBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtRGBjfActionPerformed

    private void jFmtDataRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientesBjf dialog = new JDlgClientesBjf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboEstado;
    private javax.swing.JFormattedTextField jFmtCEP;
    private javax.swing.JFormattedTextField jFmtCPFBjf;
    private javax.swing.JFormattedTextField jFmtCodigo;
    private javax.swing.JFormattedTextField jFmtDataNasc;
    private javax.swing.JTextField jFmtDataRegistro;
    private javax.swing.JFormattedTextField jFmtRGBjf;
    private javax.swing.JFormattedTextField jFmtTelefoneBjf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNaturalidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEndereço;
    private javax.swing.JTextField jTxtEstado;
    private javax.swing.JTextField jTxtNomeBjf;
    private javax.swing.JFormattedTextField jTxtProfissao;
    // End of variables declaration//GEN-END:variables

    
}
