package bean;
// Generated 13/09/2023 17:40:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FuncionarioBjf generated by hbm2java
 */
@Entity
@Table(name="funcionario_bjf"
    ,catalog="db_bianca_ferraz"
)
public class FuncionarioBjf  implements java.io.Serializable {


     private int idfuncionarioBjf;
     private UsuariosBjf usuariosBjf;
     private String nomeBjf;
     private String emailBjf;
     private String numeroTelefoneBjf;
     private String cpfBjf;
     private String sexoBjf;
     private String departamentoBjf;
     private BigDecimal salarioBjf;
     private VendasBjf vendasBjf;

    public FuncionarioBjf() {
    }

	
    public FuncionarioBjf(UsuariosBjf usuariosBjf, String nomeBjf, String emailBjf, String numeroTelefoneBjf, String cpfBjf, String sexoBjf, String departamentoBjf, BigDecimal salarioBjf) {
        this.usuariosBjf = usuariosBjf;
        this.nomeBjf = nomeBjf;
        this.emailBjf = emailBjf;
        this.numeroTelefoneBjf = numeroTelefoneBjf;
        this.cpfBjf = cpfBjf;
        this.sexoBjf = sexoBjf;
        this.departamentoBjf = departamentoBjf;
        this.salarioBjf = salarioBjf;
    }
    public FuncionarioBjf(UsuariosBjf usuariosBjf, String nomeBjf, String emailBjf, String numeroTelefoneBjf, String cpfBjf, String sexoBjf, String departamentoBjf, BigDecimal salarioBjf, VendasBjf vendasBjf) {
       this.usuariosBjf = usuariosBjf;
       this.nomeBjf = nomeBjf;
       this.emailBjf = emailBjf;
       this.numeroTelefoneBjf = numeroTelefoneBjf;
       this.cpfBjf = cpfBjf;
       this.sexoBjf = sexoBjf;
       this.departamentoBjf = departamentoBjf;
       this.salarioBjf = salarioBjf;
       this.vendasBjf = vendasBjf;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="usuariosBjf"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idfuncionario_bjf", unique=true, nullable=false)
    public int getIdfuncionarioBjf() {
        return this.idfuncionarioBjf;
    }
    
    public void setIdfuncionarioBjf(int idfuncionarioBjf) {
        this.idfuncionarioBjf = idfuncionarioBjf;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public UsuariosBjf getUsuariosBjf() {
        return this.usuariosBjf;
    }
    
    public void setUsuariosBjf(UsuariosBjf usuariosBjf) {
        this.usuariosBjf = usuariosBjf;
    }

    
    @Column(name="nome_bjf", nullable=false, length=50)
    public String getNomeBjf() {
        return this.nomeBjf;
    }
    
    public void setNomeBjf(String nomeBjf) {
        this.nomeBjf = nomeBjf;
    }

    
    @Column(name="email_bjf", nullable=false, length=50)
    public String getEmailBjf() {
        return this.emailBjf;
    }
    
    public void setEmailBjf(String emailBjf) {
        this.emailBjf = emailBjf;
    }

    
    @Column(name="numeroTelefone_bjf", nullable=false, length=14)
    public String getNumeroTelefoneBjf() {
        return this.numeroTelefoneBjf;
    }
    
    public void setNumeroTelefoneBjf(String numeroTelefoneBjf) {
        this.numeroTelefoneBjf = numeroTelefoneBjf;
    }

    
    @Column(name="cpf_bjf", nullable=false, length=15)
    public String getCpfBjf() {
        return this.cpfBjf;
    }
    
    public void setCpfBjf(String cpfBjf) {
        this.cpfBjf = cpfBjf;
    }

    
    @Column(name="sexo_bjf", nullable=false, length=1)
    public String getSexoBjf() {
        return this.sexoBjf;
    }
    
    public void setSexoBjf(String sexoBjf) {
        this.sexoBjf = sexoBjf;
    }

    
    @Column(name="departamento_bjf", nullable=false, length=50)
    public String getDepartamentoBjf() {
        return this.departamentoBjf;
    }
    
    public void setDepartamentoBjf(String departamentoBjf) {
        this.departamentoBjf = departamentoBjf;
    }

    
    @Column(name="salario_bjf", nullable=false, precision=12)
    public BigDecimal getSalarioBjf() {
        return this.salarioBjf;
    }
    
    public void setSalarioBjf(BigDecimal salarioBjf) {
        this.salarioBjf = salarioBjf;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="clienteBjf")
    public VendasBjf getVendasBjf() {
        return this.vendasBjf;
    }
    
    public void setVendasBjf(VendasBjf vendasBjf) {
        this.vendasBjf = vendasBjf;
    }




}


