package bean;
// Generated 22/09/2023 08:51:22 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoVendasBjf generated by hbm2java
 */
@Entity
@Table(name="produto_vendas_bjf"
    ,catalog="db_bianca_ferraz"
)
public class ProdutoVendasBjf  implements java.io.Serializable {


     private int idprodutoVendasBjf;
     private ProdutoBjf produtoBjf;
     private int quantidadeBjf;
     private int valorUnitarioBjf;

    public ProdutoVendasBjf() {
    }

	
    public ProdutoVendasBjf(int idprodutoVendasBjf, int quantidadeBjf, int valorUnitarioBjf) {
        this.idprodutoVendasBjf = idprodutoVendasBjf;
        this.quantidadeBjf = quantidadeBjf;
        this.valorUnitarioBjf = valorUnitarioBjf;
    }
    public ProdutoVendasBjf(int idprodutoVendasBjf, ProdutoBjf produtoBjf, int quantidadeBjf, int valorUnitarioBjf) {
       this.idprodutoVendasBjf = idprodutoVendasBjf;
       this.produtoBjf = produtoBjf;
       this.quantidadeBjf = quantidadeBjf;
       this.valorUnitarioBjf = valorUnitarioBjf;
    }
   
     @Id 

    
    @Column(name="idproduto_vendas_bjf", unique=true, nullable=false)
    public int getIdprodutoVendasBjf() {
        return this.idprodutoVendasBjf;
    }
    
    public void setIdprodutoVendasBjf(int idprodutoVendasBjf) {
        this.idprodutoVendasBjf = idprodutoVendasBjf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_produto_bjf")
    public ProdutoBjf getProdutoBjf() {
        return this.produtoBjf;
    }
    
    public void setProdutoBjf(ProdutoBjf produtoBjf) {
        this.produtoBjf = produtoBjf;
    }

    
    @Column(name="quantidade_bjf", nullable=false)
    public int getQuantidadeBjf() {
        return this.quantidadeBjf;
    }
    
    public void setQuantidadeBjf(int quantidadeBjf) {
        this.quantidadeBjf = quantidadeBjf;
    }

    
    @Column(name="valorUnitario_bjf", nullable=false)
    public int getValorUnitarioBjf() {
        return this.valorUnitarioBjf;
    }
    
    public void setValorUnitarioBjf(int valorUnitarioBjf) {
        this.valorUnitarioBjf = valorUnitarioBjf;
    }




}


