package bean;
// Generated 13/09/2023 17:40:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProdutoVendasBjf generated by hbm2java
 */
@Entity
@Table(name="produto_vendas_bjf"
    ,catalog="db_bianca_ferraz"
)
public class ProdutoVendasBjf  implements java.io.Serializable {


     private int idprodutoVendasBjf;
     private ProdutoBjf produtoBjf;
     private VendasBjf vendasBjf;
     private int quantidadeBjf;
     private int valorUnitarioBjf;

    public ProdutoVendasBjf() {
    }

    public ProdutoVendasBjf(ProdutoBjf produtoBjf, VendasBjf vendasBjf, int quantidadeBjf, int valorUnitarioBjf) {
       this.produtoBjf = produtoBjf;
       this.vendasBjf = vendasBjf;
       this.quantidadeBjf = quantidadeBjf;
       this.valorUnitarioBjf = valorUnitarioBjf;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="produtoBjf"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idproduto_vendas_bjf", unique=true, nullable=false)
    public int getIdprodutoVendasBjf() {
        return this.idprodutoVendasBjf;
    }
    
    public void setIdprodutoVendasBjf(int idprodutoVendasBjf) {
        this.idprodutoVendasBjf = idprodutoVendasBjf;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public ProdutoBjf getProdutoBjf() {
        return this.produtoBjf;
    }
    
    public void setProdutoBjf(ProdutoBjf produtoBjf) {
        this.produtoBjf = produtoBjf;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public VendasBjf getVendasBjf() {
        return this.vendasBjf;
    }
    
    public void setVendasBjf(VendasBjf vendasBjf) {
        this.vendasBjf = vendasBjf;
    }

    
    @Column(name="quantidade_bjf", nullable=false)
    public int getQuantidadeBjf() {
        return this.quantidadeBjf;
    }
    
    public void setQuantidadeBjf(int quantidadeBjf) {
        this.quantidadeBjf = quantidadeBjf;
    }

    
    @Column(name="valorUnitario_bjf", nullable=false)
    public int getValorUnitarioBjf() {
        return this.valorUnitarioBjf;
    }
    
    public void setValorUnitarioBjf(int valorUnitarioBjf) {
        this.valorUnitarioBjf = valorUnitarioBjf;
    }




}


